version: '3.8'

networks:
  myAppNetwork:
    driver: bridge

services:
  Db:
    container_name: Db
    image: postgres:17.7
    restart: unless-stopped  # Add automatic restart
    networks:
      - myAppNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U borisgarin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "borisgarin"
      POSTGRES_PASSWORD: "borisgarin"
      POSTGRES_DB: "Metarankings"
    ports:
      - "5432:5432"  # Optional, for debugging

  WebApi:
    container_name: APIContainer
    image: ${DOCKER_REGISTRY-}api
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - myAppNetwork
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      Db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Host=Db;Database=Metarankings;User Id=borisgarin;Password=borisgarin
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./API/Games/Images:/app/Games:rw
      - ./API/Movies/Images:/app/Movies:rw

volumes:
  postgres_data: