networks:
  myAppNetwork:
    driver: bridge

services:
  Db:
    container_name: Db
    image: postgres:17.7
    networks:
      - myAppNetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U borisgarin -d Metarankings" ]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "borisgarin"
      POSTGRES_PASSWORD: "borisgarin"
      POSTGRES_DB: "Metarankings"

  WebApi:
    container_name: APIContainer
    image: ${DOCKER_REGISTRY-}api
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - myAppNetwork
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      Db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=UmbracoFuse8_2023!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./API/Games/Images:/app/Games:rw  # Mount local directory to container
      - ./API/Movies/Images:/app/Movies:rw

volumes:
  postgres_data: