<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<UserSecretsId>11542b90-98c9-4fe0-a75d-746fe381ebc0</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\API.xml</DocumentationFile>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Properties\launchSettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNet.Security.OAuth.GitHub" Version="10.0.0" />
		<PackageReference Include="AspNet.Security.OAuth.MailRu" Version="10.0.0" />
		<PackageReference Include="AspNet.Security.OAuth.VkId" Version="10.0.0" />
		<PackageReference Include="AspNet.Security.OAuth.Vkontakte" Version="10.0.0" />
		<PackageReference Include="AspNet.Security.OAuth.Yandex" Version="10.0.0" />
		<PackageReference Include="FluentMigrator" Version="8.0.1" />
		<PackageReference Include="FluentMigrator.Console" Version="8.0.1" />
		<PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Twitter" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BlazorClient\BlazorClient.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Data\Data.csproj" />
		<ProjectReference Include="..\ExcelProcessors\ExcelProcessors.csproj" />
		<ProjectReference Include="..\IdentityLibrary\IdentityLibrary.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="Properties\PublishProfiles\FolderProfile.pubxml" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="SettingsDtos\" />
		<Folder Include="Workers\" />
	</ItemGroup>

</Project>
